language: scala
scala:
- 2.10.1
jdk:
- oraclejdk7
before_script:
- psql -U postgres -c "CREATE USER enricher WITH password 'supersecret1';"
- psql -U postgres -c "CREATE DATABASE sql_enrichment_test WITH OWNER = enricher;"
- psql -U postgres -d sql_enrichment_test < integration-tests/sql-enrichment-test.sql
- psql -U postgres -d sql_enrichment_test -c "GRANT ALL ON enrichment_test TO enricher;"
script:
- python integration-tests/api-lookup-test.py &
- cd 3-enrich/scala-common-enrich
- sbt test
- cd ../..
env:
  global:
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
addons:
  postgresql: '9.3'
services:
- postgresql
before_deploy:
  - pip install --user release-manager==0.2.0
deploy:
  - provider: script
    script: ./.travis/deploy_kinesis.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: '"$(.travis/is_kinesis_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
  - provider: script
    script: ./.travis/deploy_hadoop_enrich.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: '"$(.travis/is_hadoop_enrich_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
  - provider: script
    script: ./.travis/deploy_hadoop_shred.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: '"$(.travis/is_hadoop_shred_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
  - provider: script
    script: ./.travis/deploy_hadoop_enrich.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: '"$(.travis/is_hadoop_event_recovery_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
  - provider: script
    script: ./.travis/deploy_emr.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: '"$(.travis/is_emr_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
